# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'speech_hack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for speech_hack
    pod 'ApiAI'
end
