# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'URApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URApp
  pod 'ARCharts'
  pod 'Jelly', '~> 2.0'
  # Pods for speech_hack
  pod 'ApiAI'
  
  #Send Message TextInput
  pod 'Toolbar'
  pod 'IJProgressView', :git => 'https://github.com/Isuru-Nanayakkara/IJProgressView.git'
  pod 'SwiftSocket'
  pod 'LGButton'
  #Messages TableView
  #pod 'ReverseExtension'
end
