#! /bin/sh
# /etc/init.d/alexa_control
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if [ ! -f /var/lock/alexa_control ]; then

      touch /var/lock/alexa_control
      /usr/local/bin/python3.7 /root/services/alexa_server/alexa_control.py >> /var/log/alexa_control.log 2>&1 &
      if [ $? -ne 0 ]; then
        echo "Exiting with error code"
        rm /var/lock/alexa_control
      else
        echo 'Started successfully!'
      fi

    else
      echo "alexa_control already running..."
    fi
    ;;
  stop)
    pkill -15 -f alexa_control.py
    if [ $? -ne 0 ]; then
      echo "Unable to kill process alexa_control"
    fi
    rm /var/lock/alexa_control
    ;;
  *)
    echo "Usage: /etc/init.d/alexa_control {start|stop}"
    exit 1
    ;;
esac

exit 0
