#! /bin/sh
# /etc/init.d/alexa_action
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if [ ! -f /var/lock/alexa_action ]; then
      echo 'Starting ur_server...'
      touch /var/lock/alexa_action
      /usr/local/bin/python3.7 /root/services/alexa_server/alexa_action.py >> /var/log/alexa_action.log 2>&1 &
      if [ $? -ne 0 ]; then
        echo "Exiting with error code"
        rm /var/lock/alexa_action
      else
        echo 'Started successfully!'
      fi

    else
      echo "alexa_action already running..."
    fi
    ;;
  stop)
    pkill -15 -f alexa_action.py
    if [ $? -ne 0 ]; then
      echo "Unable to kill process alexa_action"
    fi
    rm /var/lock/alexa_action
    ;;
  *)
    echo "Usage: /etc/init.d/alexa_action {start|stop}"
    exit 1
    ;;
esac

exit 0
