#! /bin/sh
# /etc/init.d/ur_websocket_server
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if [ ! -f /var/lock/ur_websocket_server ]; then

      touch /var/lock/ur_websocket_server
      /usr/local/bin/python3.7 /root/services/websockets_server/websocket_server.py >> /var/log/ur_websocket_server.log 2>&1 &
      if [ $? -ne 0 ]; then
        echo "Exiting with error code"
        rm /var/lock/ur_websocket_server
      fi

    else
      echo "Websocket service already running..."
    fi
    ;;
  stop)
    pkill -15 -f websocket_server.py
    if [ $? -ne 0 ]; then
      echo "Unable to kill process ur_websocket_server"
    fi
    rm /var/lock/ur_websocket_server
    ;;
  *)
    echo "Usage: /etc/init.d/ur_websocket_server {start|stop}"
    exit 1
    ;;
esac

exit 0
