#! /bin/sh
# /etc/init.d/ur_server
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if [ ! -f /var/lock/ur_server ]; then

      touch /var/lock/ur_server
      /usr/bin/python /root/server/ur_server.py --working_path /root/server/ >> /var/log/ur_server.log 2>&1
      if [ $? -ne 0 ]; then
        echo "Unable to start process ur_server"
        rm /var/lock/ur_server
      fi

    else
      echo "Service already running..."
    fi
    ;;
  stop)
    pkill -15 -f ur_server.py
    if [ $? -ne 0 ]; then
      echo "Unable to kill process ur_server"
    else
      rm /var/lock/ur_server
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/ur_server {start|stop}"
    exit 1
    ;;
esac

exit 0
